// AUTO-GENERATED — DO NOT EDIT MANUALLY
// Generated by: scripts/generate-env-config.js
// Source: .env
// This file is gitignored. Regenerate with: npm run env:generate

(function () {
  window.__ENV__ = {
    SUPABASE_URL: "",
    SUPABASE_ANON_KEY: "",
    FIREBASE_API_KEY: "",
    FIREBASE_AUTH_DOMAIN: "",
    FIREBASE_PROJECT_ID: "",
    FIREBASE_STORAGE_BUCKET: "",
    FIREBASE_MESSAGING_SENDER_ID: "",
    FIREBASE_APP_ID: "",
    GEMINI_API_KEY: "",
  };
  console.log("[EcoShare] Environment config loaded. Provider keys present:", {
    supabase: !!(window.__ENV__.SUPABASE_URL && window.__ENV__.SUPABASE_ANON_KEY),
    firebase: !!(window.__ENV__.FIREBASE_API_KEY && window.__ENV__.FIREBASE_PROJECT_ID),
    gemini: !!window.__ENV__.GEMINI_API_KEY,
  });
})();